echo "==> Cora"
python train.py --dataset="cora"
echo "==> Pubmed"
python train.py --dataset="pubmed"
echo "==> Citeseer"
python train.py --dataset="citeseer"
echo "==> Chameleon"
python train.py --dataset="chameleon"
echo "==> Squirrel"
python train.py --dataset="squirrel"
echo "==> Amazon Computers"
python train.py --dataset="computers"
echo "==> Amazon Photo"
python train.py --dataset="photo"